let STATUS = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  WAITING_FOR_VALIDATION: "WAITING_FOR_VALIDATION",
  COMPLETED: "COMPLETED",
};

let STATUS_MAPPING = {
  1: "PENDING",
  2: "IN_PROGRESS",
  3: "WAITING_FOR_VALIDATION",
  4: "COMPLETED",
};

module.exports = {STATUS,STATUS_MAPPING};
